version: '3.3'
volumes:
  data:
services:
  banco_dados:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dkr_phpmyadmin
  juka:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - banco_dados
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1